name: Update index.html in my server

on:
  push:
    branches:
      - main

jobs:
  deploymycode:
    name: Deploy my code to my server
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ vars.SERVER_IP }}
      

    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Setup SSH key
        run: |
          echo $SSH_KEY64 | base64 -d > cicdkey.pem
          chmod 400 cicdkey.pem
          ssh-keygen -R $SERVER_IP || true
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}
          

      - name: Deploy the code to my server
        run: |
          ssh -i cicd.pem ubuntu@$SERVER_IP "cd /var/www/html && git pull origin main"
